version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies…"
  pre_build:
    commands:
      - echo "Preparing for build…"
  build:
    commands:
      - echo "Building docker application…"
      - docker compose -f compose.prod.yaml build
  post_build:
    commands:
      - echo "Build completed successfully!""
