version: 0.2
phases:
  install:
    commands:
      - |
        echo "Installing nvm and Node.js 20"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        nvm install 20
        nvm use 20
        node -v
  pre_build:
    commands:
      - echo Preparing for build…
  build:
    commands:
      - echo Building Next.js application…
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully!
