services:
  minimal-portfolio-prod:
    container_name: minimal-portfolio-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: darshanaswath/portfolio:latest
    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - my_network
# networks:
#   my_network:
#     external: true
